### ISSUE TITLE
Docker update not considering date

### ISSUE THREAD

**Issue by vsoch** [autamus/cuppa#3]
It looks like for latest we are just comparing the strings semantically and not considering the order in which they are added? https://github.com/autamus/cuppa/blob/0911790f92cef38d9fe19e724b93d8a09dc47e48/providers/docker/containers.go#L50-L65

This is leading to bugs in shpc where container tags are "updated" with older versions, see https://github.com/singularityhub/singularity-hpc/pull/500#issuecomment-1056324758

cc @marcodelapierre

**Comment by alecbcs** [comment]
Hey! So we actually do consider the published date of a container. The code that you linked is responsible for filtering out containers that don't match a filter if provided. I think the code you're looking for is, https://github.com/autamus/cuppa/blob/0911790f92cef38d9fe19e724b93d8a09dc47e48/results/resultset.go#L91-L103

**Comment by vsoch** [comment]
Gotcha! And I think we've discussed this in slack and know the particular issue.
